import type { GeneratedRoute, RouteCoordinate } from './RoutingService.js';
import type { WindForecast } from './WeatherService.js';
export type WindSegmentClassification = 'tailwind' | 'crosswind' | 'headwind';
export interface WindSegmentAnalysis { startCoordinate: RouteCoordinate; endCoordinate: RouteCoordinate; segmentDistanceM: number; bearingDegrees: number; relativeWindAngleDegrees: number; longitudinalWindComponentKmh: number; lateralWindComponentKmh: number; classification: WindSegmentClassification; }
export interface WindRouteAnalysis { analyzedDistanceM: number; tailwindDistanceM: number; headwindDistanceM: number; crosswindDistanceM: number; tailwindPercent: number; headwindPercent: number; crosswindPercent: number; returnTailwindDistanceM: number; returnHeadwindDistanceM: number; returnCrosswindDistanceM: number; returnTailwindPercent: number; returnHeadwindPercent: number; returnCrosswindPercent: number; averageLongitudinalComponentKmh: number; averageCrosswindComponentKmh: number; maxCrosswindComponentKmh: number; favorableWindScore: number; windSpeedKmh: number; windGustKmh: number; windDirectionDegrees: number; }
const rad=(value:number)=>value*Math.PI/180; const normalize=(value:number)=>((value%360)+360)%360;
export function bearingDegrees(a: RouteCoordinate,b: RouteCoordinate) { const y=Math.sin(rad(b.longitude-a.longitude))*Math.cos(rad(b.latitude)); const x=Math.cos(rad(a.latitude))*Math.sin(rad(b.latitude))-Math.sin(rad(a.latitude))*Math.cos(rad(b.latitude))*Math.cos(rad(b.longitude-a.longitude)); return normalize(Math.atan2(y,x)*180/Math.PI); }
export function haversineM(a:RouteCoordinate,b:RouteCoordinate) { const dLat=rad(b.latitude-a.latitude),dLon=rad(b.longitude-a.longitude); const h=Math.sin(dLat/2)**2+Math.cos(rad(a.latitude))*Math.cos(rad(b.latitude))*Math.sin(dLon/2)**2; return 2*6371000*Math.asin(Math.sqrt(h)); }
export class WindRouteAnalyzer { analyze(route:GeneratedRoute, wind:WindForecast): WindRouteAnalysis { const segments:WindSegmentAnalysis[]=[]; for(let i=1;i<route.geometry.length;i++){const a=route.geometry[i-1],b=route.geometry[i],d=haversineM(a,b);if(d<1)continue;const bearing=bearingDegrees(a,b),relative=Math.abs(((bearing-normalize(wind.windDirectionDegrees+180)+540)%360)-180),long=wind.windSpeedKmh*Math.cos(rad(relative)),lateral=Math.abs(wind.windSpeedKmh*Math.sin(rad(relative))),classification:WindSegmentClassification=relative<60?'tailwind':relative<120?'crosswind':'headwind';segments.push({startCoordinate:a,endCoordinate:b,segmentDistanceM:d,bearingDegrees:bearing,relativeWindAngleDegrees:relative,longitudinalWindComponentKmh:long,lateralWindComponentKmh:lateral,classification});} const total=segments.reduce((s,x)=>s+x.segmentDistanceM,0); const dist=(kind:WindSegmentClassification,list=segments)=>list.filter(x=>x.classification===kind).reduce((s,x)=>s+x.segmentDistanceM,0); const half=total/2; let accumulated=0; const returning:WindSegmentAnalysis[]=[]; for(const s of segments){const before=accumulated;accumulated+=s.segmentDistanceM;if(accumulated>half) returning.push({...s,segmentDistanceM:s.segmentDistanceM*Math.min(1,(accumulated-half)/s.segmentDistanceM)}); if(before>=half) returning[returning.length-1]=s;} const percent=(value:number,base:number)=>base?value/base*100:0; const weighted=(fn:(s:WindSegmentAnalysis)=>number)=>total?segments.reduce((sum,s)=>sum+fn(s)*s.segmentDistanceM,0)/total:0; const rt=returning.reduce((s,x)=>s+x.segmentDistanceM,0),tail=dist('tailwind'),head=dist('headwind'),cross=dist('crosswind'),rTail=dist('tailwind',returning),rHead=dist('headwind',returning),rCross=dist('crosswind',returning); return {analyzedDistanceM:total,tailwindDistanceM:tail,headwindDistanceM:head,crosswindDistanceM:cross,tailwindPercent:percent(tail,total),headwindPercent:percent(head,total),crosswindPercent:percent(cross,total),returnTailwindDistanceM:rTail,returnHeadwindDistanceM:rHead,returnCrosswindDistanceM:rCross,returnTailwindPercent:percent(rTail,rt),returnHeadwindPercent:percent(rHead,rt),returnCrosswindPercent:percent(rCross,rt),averageLongitudinalComponentKmh:weighted(x=>x.longitudinalWindComponentKmh),averageCrosswindComponentKmh:weighted(x=>x.lateralWindComponentKmh),maxCrosswindComponentKmh:Math.max(0,...segments.map(x=>x.lateralWindComponentKmh)),favorableWindScore:Math.max(0,Math.min(100,percent(rTail,rt)+percent(rCross,rt)*0.5)),windSpeedKmh:wind.windSpeedKmh,windGustKmh:wind.windGustKmh,windDirectionDegrees:wind.windDirectionDegrees}; } }
